import React from 'react';
import { Button, Card, CardHeader, CardTitle, CardContent, CardFooter } from '../components';
import { theme } from '../theme';

const ReportContent: React.FC = () => {
  return (
    <div>
      <div style={{ display: 'flex', gap: theme.spacing.medium, marginBottom: theme.spacing.large }}>
        <Button>Select Template</Button>
        <Button>Select Client</Button>
        <Button>Send</Button>
      </div>
      <Card style={{ marginBottom: theme.spacing.large }}>
        <CardHeader>
          <CardTitle>Audit Trail</CardTitle>
        </CardHeader>
        <CardContent>
          <ul style={{ listStyle: 'none', padding: 0 }}>
            <li style={{ marginBottom: theme.spacing.small }}>2023-07-09 14:30 - Data import completed by System</li>
            <li style={{ marginBottom: theme.spacing.small }}>2023-07-09 15:15 - Report generated by AI</li>
            <li style={{ marginBottom: theme.spacing.small }}>2023-07-09 16:00 - Report reviewed by Jane Smith</li>
            <li>2023-07-09 16:30 - Report approved by Mike Johnson</li>
          </ul>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Security Measures</CardTitle>
        </CardHeader>
        <CardContent>
          <ul style={{ listStyle: 'none', padding: 0 }}>
            <li style={{ display: 'flex', alignItems: 'center', marginBottom: theme.spacing.small }}>
              <span style={{ color: theme.colors.accent.primary, marginRight: theme.spacing.small }}>🔒</span>
              End-to-end encryption
            </li>
            <li style={{ display: 'flex', alignItems: 'center', marginBottom: theme.spacing.small }}>
              <span style={{ color: theme.colors.accent.primary, marginRight: theme.spacing.small }}>🔒</span>
              Two-factor authentication enabled
            </li>
            <li style={{ display: 'flex', alignItems: 'center' }}>
              <span style={{ color: theme.colors.accent.primary, marginRight: theme.spacing.small }}>🔒</span>
              Regular security audits
            </li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
};

export default ReportContent;